- name: add getConfig method ansible management block(begin)
  lineinfile:
    path: "{{ wwwsqldesigner_dest }}/backend/{{ item }}/index.php"
    insertbefore: "public static function getConfig\\(\\$id\\)"
    line: //BEGIN getConfig method ANSIBLE MANAGED BLOCK
- name: add getConfig method ansible management block(end)
  lineinfile:
    path: "{{ wwwsqldesigner_dest }}/backend/{{ item }}/index.php"
    insertbefore: "public \\$what = '';"
    line: //END getConfig method ANSIBLE MANAGED BLOCK
- name: replace getConfig method
  blockinfile:
    path: "{{ wwwsqldesigner_dest }}/backend/{{ item }}/index.php"
    marker: //{mark} getConfig method ANSIBLE MANAGED BLOCK
    block: |
      public static function getConfig($id)
      {
          switch($id)
          {
              case 'saveloadlist':
                  $type = '{{ wwwsqldesigner_backend_pdo_cfg.save.type }}';
                  $dsn = '{{ wwwsqldesigner_backend_pdo_cfg.save.dsn }}';
                  $user = '{{ wwwsqldesigner_backend_pdo_cfg.save.user }}';
                  $password = '{{ wwwsqldesigner_backend_pdo_cfg.save.password }}';
                  $table = '{{ wwwsqldesigner_backend_pdo_cfg.save.table|default('wwwsqldesigner') }}';
                  return array($type, $dsn, $user, $password, $table);
              case 'import':
                  $type = '{{ wwwsqldesigner_backend_pdo_cfg.import.type }}';
                  $dsn = '{{ wwwsqldesigner_backend_pdo_cfg.import.dsn }}';
                  $user = '{{ wwwsqldesigner_backend_pdo_cfg.import.user }}';
                  $password = '{{ wwwsqldesigner_backend_pdo_cfg.import.password }}';
                  return array($type, $dsn, $user, $password);
          }
      }
