- name: replace save action database setting
  blockinfile:
    path: "{{ wwwsqldesigner_dest }}/backend/{{ item }}/index.php"
    marker: "# {mark} saveloadlist ANSIBLE MANAGED BLOCK"
    block: |
      $type = '{{ wwwsqldesigner_backend_pdo_cfg.save.type }}';
      $dsn = '{{ wwwsqldesigner_backend_pdo_cfg.save.dsn }}';
      $user = '{{ wwwsqldesigner_backend_pdo_cfg.save.user }}';
      $password = '{{ wwwsqldesigner_backend_pdo_cfg.save.password }}';
      $table = '{{ wwwsqldesigner_backend_pdo_cfg.save.table|default('wwwsqldesigner') }}';
- name: replace import action database setting
  blockinfile:
    path: "{{ wwwsqldesigner_dest }}/backend/{{ item }}/index.php"
    marker: "# {mark} import ANSIBLE MANAGED BLOCK"
    block: |
      $type = '{{ wwwsqldesigner_backend_pdo_cfg.import.type }}';
      $dsn = '{{ wwwsqldesigner_backend_pdo_cfg.import.dsn }}';
      $user = '{{ wwwsqldesigner_backend_pdo_cfg.import.user }}';
      $password = '{{ wwwsqldesigner_backend_pdo_cfg.import.password }}';
